export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_COMPLETED = 'SHOW_COMPLETED';
export const SHOW_PENDING = 'SHOW_PENDING';

export const SORT_CREATED_DATE_NONE = 'SORT_CREATED_DATE_NONE';
export const SORT_CREATED_DATE_UP = 'SORT_CREATED_DATE_UP';
export const SORT_CREATED_DATE_DOWN = 'SORT_CREATED_DATE_DOWN';